### PR TITLE
clipboard option added to cli

### PR DESCRIPTION
**Pull request by oscarsaleta**
This pull request solves issue <a href="https://github.com/lesspass/lesspass/issues/117">#117</a> (in the main repo).

The name of the option is `--clipboard` (short form `-C`), it is false by default.

### CODE REVIEW

**Comment by trygveaa** [comment]
I think it should clear the clipboard after the password has been pasted one time, so you don't accidentally paste the password to other places. At least on Linux with xclip, this can be done by passing the `-l 1` option.

**Comment by oscarsaleta** [comment]
@trygveaa How would you go about it? I'm not sure the <a href="https://github.com/xavi-/node-copy-paste">copy-paste</a> module I used here supports passing arguments to the xclip command, maybe this would be a feature request for that utility.

**Comment by trygveaa** [comment]
Yes, seems like one would have to patch that tool.

**Comment by edouard-lopez** [comment]
@oscarsaleta could you install [`xo`](https://github.com/sindresorhus/xo/), run it on the code and fix issue related to your PR ?

**Comment by guillaumevincent** [comment]
@edouard-lopez we should do this :)

**Pull request merged**
