### PR TITLE
Replace copy-paste with clipboardy

### PR DESCRIPTION
**Pull request by mlcdf**
Related to lesspass/lesspass#153

Let me know what you think.

(I didn't write any tests since I wasn't sure how to properly test this.)

### CODE REVIEW

**Comment by mlcdf** [comment]
Arf, that was I afraid of.

I'll to update the .travis.yml to install `xsel` before running the tests.

**Comment by guillaumevincent** [comment]
@mlcdf 

https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-on-Standard-Infrastructure

Maybe with just this in .travis.yml

```
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xsel
```

**Comment by guillaumevincent** [comment]
There is already a test for the clipboard: https://github.com/lesspass/cli/blob/master/test.js#L9-L12

It's ok to check that with xsel installed, the command line print `Copied to clipboard`.

**Comment by mlcdf** [comment]
Regarding Travis, that's what I tried but it didn't work: https://travis-ci.org/mlcdf/cli/builds

Here's the 2 errors: 
```
  ✖ options can be before parameters Error: Command failed: ./cli.js -C lesspass.com contact@lesspass.com password

events.js:141

      throw er; // Unhandled 'error' event

      ^

Error: write EPIPE

    at exports._errnoException (util.js:907:11)

    at WriteWrap.afterWrite (net.js:787:14)

...

  ✖ long options can be before parameters Error: Command failed: ./cli.js --clipboard lesspass.com contact@lesspass.com password

events.js:141

      throw er; // Unhandled 'error' event

      ^

Error: write EPIPE

    at exports._errnoException (util.js:907:11)

    at WriteWrap.afterWrite (net.js:787:14)


```

I'm not sure how to fix this. I'll take (fresh) another look tomorrow.

**Comment by guillaumevincent** [comment]
Does `npm test` work on your computer? If yes it's a travis configuration problem.
I will take a look too

**Comment by mlcdf** [comment]
Yes, it work fine. 
And the commands `./cli.js --clipboard lesspass.com contact@lesspass.com password` and `./cli.js -C lesspass.com contact@lesspass.com password` also work.

I try restarting the build, but it didn't work either. ;(

**Comment by guillaumevincent** [comment]
I close this one because I've merged this one https://github.com/lesspass/cli/pull/4

**Pull request closed without merging**
